let isEditing=false;
let currentTheme='slate';
let currentLang='en';
const STORAGE_KEY='marriage_biodata_shared_v3';
const PHOTO_KEY='marriage_biodata_photo_v3';
const labels={en:{'btn-edit':'Edit Info','btn-save':'Save Changes','btn-print':'Print / PDF','lbl-upload':'Click to Upload Profile Photo','lbl-change':'Change Photo','lbl-dob':'Date of Birth','lbl-tob':'Time of Birth','lbl-pob':'Place of Birth','lbl-height':'Height','lbl-rashi':'Rashi','lbl-gotra':'Gotra','lbl-community':'Community','lbl-diet':'Diet','lbl-edit-helper':'Click on any text to edit directly.','tab-career':'Career & Edu','tab-family':'Family Details','tab-lifestyle':'Lifestyle','tab-contact':'Contact','sec-edu':'Education (Brief)','sec-job':'Career & Job Duties','lbl-edu-c1':'Centennial College (2023)','lbl-edu-c2':'Centennial College (2022)','lbl-edu-u1':'RKDF University (2018)','lbl-job-date1':'August 2025 - Present','lbl-job-date2':'November 2023 - Present','lbl-job-date3':'August 2018 - August 2021','sec-family':'Family Details (Brief)','lbl-father':'Father','lbl-mother':'Mother','lbl-brother':'Brother','lbl-sister':'Sister','sec-settlement':'Settlement Status','sec-adventures':'Favorite Adventures','hb-sky':'Sky Diving','hb-sky-desc':'Loved the ultimate free-fall thrill','hb-raft':'River Rafting','hb-raft-desc':'Navigating strong rapids','hb-hike':'Hiking','hb-hike-desc':'Scaling majestic mountain trails','hb-scuba':'Scuba Diving','hb-scuba-desc':'Exploring deep underwater realms','hb-mountain':'Mountains','hb-mountain-desc':'Elevated views & crisp air','hb-cloud':'Cloudscapes','hb-cloud-desc':'Watching shifting cloud details','sec-contact':'Contact & Socials','lbl-phone':'Phone','lbl-email':'Email','lbl-linkedin':'LinkedIn','lbl-instagram':'Instagram','lbl-address':'Residence Address','sec-share':'Quick Share','desc-share':'You can copy a pre-formatted WhatsApp-friendly summary of the bio-data to share directly with family, friends, or matchmakers.','btn-share':'Copy WhatsApp Summary','toast-saved':'Changes saved successfully!','toast-edit':'Edit mode active. Click any text to modify.','toast-photo':'Profile photo updated!','toast-copied':'WhatsApp summary copied!'},hi:{},gu:{}};
labels.hi=labels.en;labels.gu=labels.en;
function t(key){return(labels[currentLang]&&labels[currentLang][key])||labels.en[key]||key}
function allEditable(){return Array.from(document.querySelectorAll('[data-key]'))}
function saveToStorage(){const data={};allEditable().forEach(el=>data[el.dataset.key]=el.innerHTML);localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function loadFromStorage(){try{const data=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');allEditable().forEach(el=>{if(Object.prototype.hasOwnProperty.call(data,el.dataset.key))el.innerHTML=data[el.dataset.key]})}catch(e){console.warn('Could not load saved bio-data',e)}}
function applyUILabels(){document.querySelectorAll('[data-ui-key]').forEach(el=>{el.textContent=t(el.dataset.uiKey)});const editBtnText=document.getElementById('edit-btn-text');if(editBtnText)editBtnText.textContent=isEditing?t('btn-save'):t('btn-edit')}
function setTheme(theme){document.body.className=`theme-${theme}`+(isEditing?' edit-active':'');document.querySelectorAll('.theme-dot').forEach(d=>d.classList.remove('active'));const dot=document.querySelector(`.dot-${theme}`);if(dot)dot.classList.add('active');currentTheme=theme;localStorage.setItem('marriage_biodata_theme',theme)}
function setLanguage(lang){if(isEditing)saveToStorage();currentLang=lang;localStorage.setItem('marriage_biodata_lang',lang);document.querySelectorAll('.lang-btn').forEach(b=>b.classList.remove('active'));const btn=document.getElementById(`lang-${lang}`);if(btn)btn.classList.add('active');applyUILabels()}
function switchTab(event,tabId){document.querySelectorAll('.tab-content').forEach(c=>c.classList.remove('active'));document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));const tab=document.getElementById(tabId);if(tab)tab.classList.add('active');if(event)event.currentTarget.classList.add('active')}
function toggleEditMode(){isEditing=!isEditing;const btn=document.getElementById('edit-btn');const txt=document.getElementById('edit-btn-text');if(isEditing){document.body.classList.add('edit-active');if(txt)txt.textContent=t('btn-save');if(btn)btn.style.cssText='background:#22c55e;color:#fff;border-color:#22c55e;';allEditable().forEach(el=>el.setAttribute('contenteditable','true'));showToast(t('toast-edit'),'#e2b857')}else{saveToStorage();document.body.classList.remove('edit-active');if(txt)txt.textContent=t('btn-edit');if(btn)btn.style.cssText='';allEditable().forEach(el=>el.setAttribute('contenteditable','false'));showToast(t('toast-saved'),'#22c55e')}}
function triggerPhotoUpload(){document.getElementById('photo-file-input').click()}
function loadPhoto(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=e=>{const img=document.getElementById('profile-img');const ph=document.getElementById('img-placeholder');img.src=e.target.result;img.style.display='block';ph.style.display='none';localStorage.setItem(PHOTO_KEY,e.target.result);showToast(t('toast-photo'),'#22c55e')};reader.readAsDataURL(file)}
function loadPhotoFromStorage(){const src=localStorage.getItem(PHOTO_KEY);if(!src)return;const img=document.getElementById('profile-img');const ph=document.getElementById('img-placeholder');if(img&&ph){img.src=src;img.style.display='block';ph.style.display='none'}}
function showToast(message,bgColor){const toast=document.getElementById('toast');const msg=document.getElementById('toast-message');if(!toast||!msg)return;toast.style.background=bgColor||'#22c55e';msg.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3000)}
function textOf(id){const el=document.getElementById(id);return el?el.innerText.replace(/\s+/g,' ').trim():''}
function copyWhatsAppSummary(){const text=`*MARRIAGE BIO-DATA*\n\n*PERSONAL DETAILS*\n- Date of Birth: ${textOf('val-dob')}\n- Height: ${textOf('val-height')}\n- Rashi: ${textOf('val-rashi')}\n- Gotra: ${textOf('val-gotra')}\n- Community: ${textOf('val-community')}\n- Diet: ${textOf('val-diet')}\n\n*EDUCATION & CAREER*\n- ${textOf('val-edu1')}\n- ${textOf('val-edu2')}\n- ${textOf('val-edu3')}\n- ${textOf('val-designation')}\n\n*FAMILY BACKGROUND*\n- Father: ${textOf('val-father')}\n- Mother: ${textOf('val-mother')}\n- Brother: ${textOf('val-brother')}\n- Sister: ${textOf('val-sister')}\n\n*CONTACT DETAILS*\n- Phone: ${textOf('val-phone')}\n- Email: ${textOf('val-email')}\n- LinkedIn: ${textOf('val-linkedin')}\n- Instagram: ${textOf('val-instagram')}\n- Address: ${textOf('val-address')}`;navigator.clipboard.writeText(text).then(()=>showToast(t('toast-copied'),'#075e54')).catch(()=>showToast('Could not copy. Please try again.','#ef4444'))}
function initParticles(){const canvas=document.getElementById('particles-canvas');if(!canvas)return;const ctx=canvas.getContext('2d');let W=canvas.width=innerWidth,H=canvas.height=innerHeight;const makeStar=()=>({x:Math.random()*W,y:Math.random()*H,size:.45+Math.random()*1.4,alpha:Math.random(),target:Math.random(),speed:.006+Math.random()*.016,color:Math.floor(Math.random()*4)});let stars=Array.from({length:Math.min(210,Math.floor(W*H/8500))},makeStar);addEventListener('resize',()=>{W=canvas.width=innerWidth;H=canvas.height=innerHeight;stars=Array.from({length:Math.min(210,Math.floor(W*H/8500))},makeStar)});function palette(){if(currentTheme==='linen')return['rgba(255,240,210,','rgba(255,220,170,','rgba(220,180,130,','rgba(255,255,240,'];if(currentTheme==='blush')return['rgba(255,200,220,','rgba(255,170,200,','rgba(255,230,250,','rgba(255,215,157,'];return['rgba(255,255,255,','rgba(226,184,87,','rgba(200,220,255,','rgba(255,240,180,']}function draw(){ctx.clearRect(0,0,W,H);const p=palette();stars.forEach(s=>{if(Math.abs(s.alpha-s.target)<.01)s.target=.08+Math.random()*.92;s.alpha+=(s.target-s.alpha)*s.speed;const c=p[s.color];ctx.beginPath();ctx.arc(s.x,s.y,s.size,0,Math.PI*2);ctx.fillStyle=`${c}${s.alpha.toFixed(2)})`;ctx.fill();if(s.size>1.4){ctx.strokeStyle=`${c}${(s.alpha*.7).toFixed(2)})`;ctx.beginPath();ctx.moveTo(s.x-s.size*4,s.y);ctx.lineTo(s.x+s.size*4,s.y);ctx.moveTo(s.x,s.y-s.size*4);ctx.lineTo(s.x,s.y+s.size*4);ctx.stroke()}});requestAnimationFrame(draw)}draw()}
document.addEventListener('DOMContentLoaded',()=>{loadFromStorage();setTheme(localStorage.getItem('marriage_biodata_theme')||'slate');setLanguage(localStorage.getItem('marriage_biodata_lang')||'en');loadPhotoFromStorage();initParticles()});
